name: chambeape
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.3
  get: ^4.6.6

  cupertino_icons: ^1.0.2
  image_picker: ^1.1.0
  stomp_dart_client: ^2.0.0
  crypto: ^3.0.3
  dash_chat_2: ^0.0.20
  timezone: ^0.9.3
  gcloud: ^0.8.12
  googleapis_auth: ^1.6.0
  mime: ^1.0.5
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gcloud_credentials.json

  #
